spring:
  profiles:
    include: devDB, devRedis
mybatis-plus:
#  type-aliases-package: com.example.homework.pojo
#  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      cache-enabled: true
      use-generated-keys: true
feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 5000