spring:
  cache:
    type: redis
#    redis:
#      time-to-live: 60s
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000
    lettuce:
      shutdown-timeout: 1000
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms
