server:
  port: 9411
spring:
  application:
    name: zipkin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:18080/eureka/ #注册服务器地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false